default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: cubin1905
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: monika

test:
  <<: *default
  database: monika

production:
  <<: *default
  database: monika
