default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%=ENV['C9_USER']%>
  password: 
  host: <%=ENV['IP']%>

development:
  <<: *default
  database: monika2

test:
  <<: *default
  database: monika2

production:
  <<: *default
  database: monika2